--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/IcyEndymion004/Blockpets
branches:
- main
projects:
  BlockPets:
    path: ""
    icon: resources/BlockPetsLogo.png
    compressBuilds: false
    fullGzip: 9
    libs:
      - src: Falkirks/spoondetector/spoondetector
      - src: poggit/libasynql/libasynql
      - src: muqsit/invmenu/invmenu
...
